version: '3'

services:
  grpc_server:
    container_name: grpc_server
    image: grpc_server
    build:
      context: ./grpc-server
      dockerfile: ./Dockerfile
      args:
        api_key: myAPI
    ports:
      - 8080:8080
    networks:
      test_network:
        ipv4_address: 192.168.1.2
    environment:
      - api-key=myAPI
#    restart: unless-stopped
    stdin_open: true
    tty: true

  gateway:
    container_name: gateway
    image: gateway
    build:
      context: ./gateway
      dockerfile: ./Dockerfile
#    volumes:
#      - ./src/GameMaster/:/usr/src/app/
    ports:
      - 4000:4000
    networks:
      test_network:
        ipv4_address: 192.168.1.3
    environment:
      - API_HOST=grpc_server:8080
      - API_KEY=dQw4w9WgXcQ
      - AUTH_TOKEN=Token
      - PORT=4000
    depends_on:
     - grpc_server
#    command: node index.js
#    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  test_network:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.1.0/24
         gateway: 192.168.1.1